version: '3'

services:
  postgres:
    image: postgres:13.1
    container_name: test_db
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=bob
      - APP_DB_PASS=admin
      - APP_DB_NAME=mydb
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432